import type { Metadata } from "next";

import "./globals.css";
import { bebasNeue, notoSansGeorgian } from "./fonts";
import { QueryProvider } from "@/query/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ka"
      className={`${bebasNeue.variable} ${notoSansGeorgian.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col font-sans bg-[#0F011D]">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
